services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - STABILITY_API_KEY=TU_API_KEY
      - GROQ_API_KEY=TU_API_KEY
    command: >
      sh -c "python -m spacy download en_core_web_sm &&
             uvicorn server.main:app --host 0.0.0.0 --port 8000 --reload"

 frontend:
  build:
    context: .
    dockerfile: client/Dockerfile.frontend

    ports:
      - "7860:7860"
    depends_on:
      - backend
    environment:
      - PYTHONUNBUFFERED=1
    command: python app.py
