version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app/server
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "7860:7860"
    volumes:
      - ./client:/app/client
    environment:
      - PYTHONUNBUFFERED=1
      - BACKEND_URL=http://backend:8000 
    depends_on:
      - backend
